$('.loading').css('display','inline-block')
$('.bg').css('display','none')
$('nav').data('offset-top',$(window).height())
$(window).load(function(){
	$('.circle').delay(500).animate({
		height:'2000px',
		width:'2000px',
		opacity:1,
		backgroundColor:'#ccc'
	},1000).promise().done(function(){
		scrollTo(0,0)
		$('.loading').fadeOut(1000).promise().done(function(){
			$('.bg').fadeIn(1000)
		})
	})
})